name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          npm install

      # Code Style Check - Only errors
      - name: Run ESLint
        run: npm run lint -- --quiet # The --quiet flag suppresses warnings
        
      # Code Smells Analysis - Only errors
      - name: Run TypeScript Compiler Checks
        run: npx tsc --noEmit --suppressWarnings
        
      # Secret Scanning - Critical findings only
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified --fail-verified

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    name: Build & Test (Node ${{ matrix.node-version }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          npm install --no-audit
        continue-on-error: true

      - name: Retry Install on Failure
        if: failure()
        run: |
          npm cache clean --force
          npm install --no-audit

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build